export type InspectionChecklistItem = {
  category: string;
  key: string;
  label: string;
};

export const inspectionChecklist: InspectionChecklistItem[] = [
  { category: "Estrutura e acabamento", key: "front_fairing", label: "Carenagem dianteira" },
  { category: "Estrutura e acabamento", key: "left_side_fairing", label: "Carenagem lateral esquerda" },
  { category: "Estrutura e acabamento", key: "right_side_fairing", label: "Carenagem lateral direita" },
  { category: "Estrutura e acabamento", key: "tail", label: "Rabeta" },
  { category: "Estrutura e acabamento", key: "tank", label: "Tanque" },
  { category: "Estrutura e acabamento", key: "seat", label: "Banco" },
  { category: "Estrutura e acabamento", key: "visible_chassis", label: "Chassi aparente" },
  { category: "Estrutura e acabamento", key: "paint", label: "Pintura" },
  { category: "Estrutura e acabamento", key: "stickers", label: "Adesivos" },
  { category: "Estrutura e acabamento", key: "mudguards", label: "Paralamas" },
  { category: "Rodas e pneus", key: "front_tire", label: "Pneu dianteiro" },
  { category: "Rodas e pneus", key: "rear_tire", label: "Pneu traseiro" },
  { category: "Rodas e pneus", key: "front_wheel", label: "Roda dianteira" },
  { category: "Rodas e pneus", key: "rear_wheel", label: "Roda traseira" },
  { category: "Rodas e pneus", key: "rim", label: "Aro" },
  { category: "Rodas e pneus", key: "calibration", label: "Calibragem" },
  { category: "Rodas e pneus", key: "tire_condition", label: "Estado dos pneus" },
  { category: "Freios", key: "front_brake", label: "Freio dianteiro" },
  { category: "Freios", key: "rear_brake", label: "Freio traseiro" },
  { category: "Freios", key: "pads", label: "Pastilhas" },
  { category: "Freios", key: "discs", label: "Discos" },
  { category: "Freios", key: "fluid", label: "Fluido" },
  { category: "Freios", key: "lever", label: "Manete" },
  { category: "Freios", key: "pedal", label: "Pedal" },
  { category: "Eletrica", key: "low_beam", label: "Farol baixo" },
  { category: "Eletrica", key: "high_beam", label: "Farol alto" },
  { category: "Eletrica", key: "tail_light", label: "Lanterna traseira" },
  { category: "Eletrica", key: "brake_light", label: "Luz de freio" },
  { category: "Eletrica", key: "front_turn_signals", label: "Setas dianteiras" },
  { category: "Eletrica", key: "rear_turn_signals", label: "Setas traseiras" },
  { category: "Eletrica", key: "horn", label: "Buzina" },
  { category: "Eletrica", key: "panel", label: "Painel" },
  { category: "Eletrica", key: "indicators", label: "Indicadores" },
  { category: "Eletrica", key: "battery", label: "Bateria" },
  { category: "Eletrica", key: "electric_start", label: "Partida eletrica" },
  { category: "Motor e mecanica", key: "engine", label: "Motor" },
  { category: "Motor e mecanica", key: "leaks", label: "Vazamentos" },
  { category: "Motor e mecanica", key: "oil", label: "Oleo" },
  { category: "Motor e mecanica", key: "clutch", label: "Embreagem" },
  { category: "Motor e mecanica", key: "gearbox", label: "Cambio" },
  { category: "Motor e mecanica", key: "chain", label: "Corrente" },
  { category: "Motor e mecanica", key: "sprocket", label: "Coroa" },
  { category: "Motor e mecanica", key: "pinion", label: "Pinhao" },
  { category: "Motor e mecanica", key: "transmission_kit", label: "Relacao" },
  { category: "Motor e mecanica", key: "exhaust", label: "Escapamento" },
  { category: "Motor e mecanica", key: "front_suspension", label: "Suspensao dianteira" },
  { category: "Motor e mecanica", key: "rear_suspension", label: "Suspensao traseira" },
  { category: "Motor e mecanica", key: "steering", label: "Direcao" },
  { category: "Seguranca", key: "left_mirror", label: "Retrovisor esquerdo" },
  { category: "Seguranca", key: "right_mirror", label: "Retrovisor direito" },
  { category: "Seguranca", key: "handlebar", label: "Guidao" },
  { category: "Seguranca", key: "grips", label: "Manoplas" },
  { category: "Seguranca", key: "side_stand", label: "Descanso lateral" },
  { category: "Seguranca", key: "center_stand", label: "Cavalete central" },
  { category: "Seguranca", key: "locks", label: "Travas" },
  { category: "Seguranca", key: "key", label: "Chave" },
  { category: "Seguranca", key: "spare_key", label: "Chave reserva" },
  { category: "Seguranca", key: "alarm", label: "Alarme" },
  { category: "Seguranca", key: "tracker", label: "Rastreador" },
  { category: "Documentos e acessorios", key: "motorcycle_document", label: "Documento da moto" },
  { category: "Documentos e acessorios", key: "manual", label: "Manual" },
  { category: "Documentos e acessorios", key: "helmet", label: "Capacete" },
  { category: "Documentos e acessorios", key: "raincoat", label: "Capa de chuva" },
  { category: "Documentos e acessorios", key: "top_case", label: "Bau" },
  { category: "Documentos e acessorios", key: "phone_holder", label: "Suporte de celular" },
  { category: "Documentos e acessorios", key: "usb_charger", label: "Carregador USB" },
  { category: "Documentos e acessorios", key: "kite_antenna", label: "Antena corta-pipa" },
  { category: "Documentos e acessorios", key: "engine_guard", label: "Protetor de motor" },
  { category: "Documentos e acessorios", key: "other_accessories", label: "Outros acessorios" }
];

export const defaultInspectionAccessories = [
  "Capacete",
  "Chave principal",
  "Chave reserva",
  "Bau",
  "Capa de chuva",
  "Suporte de celular",
  "Carregador",
  "Antena corta-pipa",
  "Protetor de motor",
  "Outros"
];

export const requiredInspectionPhotoTypes = [
  "FRONT",
  "REAR",
  "LEFT_SIDE",
  "RIGHT_SIDE",
  "ODOMETER",
  "PLATE",
  "ENGINE",
  "FRONT_TIRE",
  "REAR_TIRE"
] as const;
